development:
  adapter: async
  url: redis://localhost:6379/1
  url: redis://localhost:6379/2
  url: redis://localhost:6379/3

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
