# encoding=utf-8

connection:
    host:        '192.168.2.62' 
    vhost:       '/'
    user:        'hujun'
    password:    '123456'

queue_lists:
    - name:   'message.BNCT' 
      invoke: 'Room.message_handler'
      subscribe_lists:
        # - name:   'OR.test'
          # invoke: 'Online::RegistersHelper.receive_subscribe_queue'

